<Project>
    <Import Project="../Directory.Build.props" />

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="../UITests.Shared/**/*.cs" LinkBase="Shared" Visible="false" />
    </ItemGroup>

    <!-- Global test packages for all test projects -->
    <ItemGroup>
        <GlobalPackageReference Include="xunit.v3" Version="3.1.0" />
        <GlobalPackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
        <GlobalPackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    </ItemGroup>
</Project>