<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.ML" Version="3.0.1" />
		<PackageReference Include="Microsoft.ML.CpuMath" Version="3.0.1" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Data\wikiDetoxAnnotated40kRows.tsv">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>