<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Bogus" Version="35.5.0" />
		<PackageReference Include="Shouldly" Version="4.2.1" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
		<PackageReference Include="Moq" Version="4.20.70" />
		<PackageReference Include="xunit" Version="2.7.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.5.7" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\App_MAUI_Enterprise.Web\App_MAUI_Enterprise.Web\App_MAUI_Enterprise.Web.csproj" />
	</ItemGroup>

</Project>