<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright.MSTest" Version="1.60.0" />
    <PackageReference Include="NUnit" Version="4.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\source\business-domain-logic-models\HolisticWare.Core.BusinessDomainLogicModels\HolisticWare.Core.BusinessDomainLogicModels.csproj" />
  </ItemGroup>

</Project>
