<Project Sdk="Microsoft.NET.Sdk">
	
	<ItemGroup>
	  <ProjectReference Include="..\..\HolisticWare.Core.UserInterfaceUI\HolisticWare.Core.UserInterfaceUI.csproj" />
	</ItemGroup>

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net10.0;net9.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>HolisticWare.Core.UserInterfaceUI.MAUI</PackageId>
    </PropertyGroup>

</Project>
