<Project Sdk="Microsoft.NET.Sdk">
	
	<ItemGroup>
	  <ProjectReference Include="..\..\HolisticWare.Core.UserInterfaceUI\HolisticWare.Core.UserInterfaceUI.csproj" />
	</ItemGroup>

    <PropertyGroup>
        <PackageId>HolisticWare.Core.UserInterfaceUI.MAUI</PackageId>
    </PropertyGroup>

</Project>
