<Project Sdk="Aspire.AppHost.Sdk/13.2.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <UserSecretsId>38808dc7-760d-4fb0-9e64-ab2070adfadc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App_Aspire_Starter.ApiService\App_Aspire_Starter.ApiService.csproj" />
    <ProjectReference Include="..\App_Aspire_Starter.Web\App_Aspire_Starter.Web.csproj" />
  </ItemGroup>

</Project>
