<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)-windows</TargetFramework>
		<OutputType>WinExe</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\App_MAUI_Enterprise.Core\App_MAUI_Enterprise.Core\App_MAUI_Enterprise.Core.csproj" />
	</ItemGroup>

</Project>